name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    env:
      VERBOSE: 1
      GOFLAGS: -mod=readonly
      GOPROXY: https://proxy.golang.org

    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Run tests
        run: make test

      - name: Run linter
        run: make lint

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          username: bskim45
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: make docker-build-image

      - name: Tag Docker Image
        run: make docker-tag

      - name: Publish Docker Image
        run: make docker-publish

#      - name: Get tag name
#        id: tag_name
#        uses: olegtarasov/get-tag@v1
#
#      - name: Release GitHub
#        uses: softprops/action-gh-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          name: v${{ steps.tag_name.outputs.tag }}
#          draft: false
#          prerelease: false
#          files: |
#            dist/dtags-*.tar.gz
#            dist/dtags-*.zip
